services:
    _defaults:
        autowire: true

    enqueue.messenger_transport.factory:
        class: 'Enqueue\MessengerAdapter\QueueInteropTransportFactory'
        arguments:
            - '@messenger.transport.decoder'
            - '@messenger.transport.encoder'
            - '@service_container'
            - '%kernel.debug%'
        tags: ['messenger.transport_factory']

    Enqueue\MessengerAdapter\Service\Contract\MessageFailLogStorageInterface:
        class: 'Enqueue\MessengerAdapter\Service\AbstractMessageFailLogStorage'

    Enqueue\MessengerAdapter\EventSubscriber\QueueInteropTransportFailSubscriber:
        tags: ['kernel.event_subscriber']
